# Generated by Django 6.0.5 on 2026-05-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrestaurantmodel',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
