# Generated by Django 6.0.5 on 2026-05-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffrestaurantmodel_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='salary',
        ),
    ]
