# Generated by Django 6.0.5 on 2026-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('MX', 'Mexican'), ('OT', 'Other')], default='IN', max_length=2),
        ),
    ]
