# Generated by Django 6.0.5 on 2026-05-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_staffmodel_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
