# Generated by Django 6.0.5 on 2026-05-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurantmodel_restaurant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.restaurantmodel')),
            ],
        ),
    ]
