# Generated by Django 6.0.5 on 2026-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salemodel_expenditure_alter_salemodel_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
