# Generated by Django 6.0.5 on 2026-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurantmodel_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
