# Generated by Django 6.0.5 on 2026-05-30 07:51

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_commentmodel_delete_dummymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('MX', 'Mexican'), ('OT', 'Other')], default='IN', max_length=2, unique=True),
        ),
        migrations.AddConstraint(
            model_name='ratingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rating__range', (1, 5))), name='rating_range', violation_error_message='Rating should be between 1 and 5'),
        ),
        migrations.AddConstraint(
            model_name='ratingmodel',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_rating_per_user_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='restaurantmodel',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__range', (-90, 90))), name='latitude_range', violation_error_message='Latitude should be between -90 and 90'),
        ),
        migrations.AddConstraint(
            model_name='restaurantmodel',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__range', (-180, 180))), name='longitude_range', violation_error_message='Longitude should be between -180 and 180'),
        ),
        migrations.AddConstraint(
            model_name='restaurantmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='check_name_unique_constraints'),
        ),
    ]
